### ISSUE TITLE
How to get your group_num?

### ISSUE THREAD

**Issue by yangzhch6** [2003pro/Graph2Tree#1]
How can I get the file "Math_23K_processed.json"?

**Comment by a773938364** [comment]
I want to ask this question, too

**Comment by 2003pro** [comment]
Let's first explain what these numbers in "group_num" means. This "group_num" represents the quantity cells mentioned in paragraph 3.1.2 of our paper. 

More accurately, these numbers indicate all the words in these quantity cells by giving their index. Each cell consists of a quantity and its corresponding attributes.

Take the problem given in your last mail as an example, we actually have these quantity cells "(4,5,7), (9,10,12), (16,17,18,19)". 

In other words, these cells are "(商是, 1.5, 如果), (增加, 20, 则), (的, 4, 倍, .)".


Next, how can we extract these cells? Also, as stated in the 3.1.2 part, we will try to extract quantity and there attributes by using synatx tools and pre-defined rules. This code is modified from https://gitlab.cs.washington.edu/ALGES/TACL2015. 

However, this synatx based methods sometimes fails. In order to avoid losing key information, I tried to use quantity with its neighbor words when synatx methods only extract 1 or 0 attributes. 



Hope this helps.

**Comment by longlongman** [comment]
Would you like to share the preprocess code with us? I am trying to use your job to solve the problem I facing right now.

**Comment by aashishwaikar** [comment]
Would it be possible to share the preprocessing code for extracting these cells and obtaining "Math_23K_processed.json"?

**Comment by 2003pro** [comment]
So sorry for responding so late, preprocessing code was stored in the account in the previous lab. The related server met troubles about bitcoins virus and my account had been removed since then. Thus, I can not found the original preprocessing code now.

**Comment by vuducanh0802** [comment]
> Each cell consists of a quantity and its corresponding attributes.

so if the text is "I have 2 cars" or "the work needs 4 hours to finish", the group num will be index of [2, cars] and [4, hours] or something like that right. What if the context is more complex like "Every hour my dad drives 16 km", will group_num catches ["every", "hour", 16, "km] or just [16, "km]

**Comment by 2003pro** [comment]
> 

Yep. We can only find simple near-neighbor-info through linguistic tools. Since our goal is to automatically get these groups, it is hard to get expected "["every", "hour", 16, "km] ". Things always varied a lot. It is hard to design linguistic pattern fitting like 20,000 examples in the training datasets.
